#!/usr/bin/env python3
"""Generate a Codex-facing export of the reusable skill corpus.

The imported repository is structured for Claude plugins and Anthropic managed
agents. This script exports the reusable markdown assets into a flat Codex
surface, applies a few safe first-pass wording rewrites, and records remaining
runtime compatibility findings for manual follow-up.
"""

from __future__ import annotations

import json
import re
import shutil
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CODEX_DIR = ROOT / "codex"
SKILLS_OUT = CODEX_DIR / "skills"
COMMANDS_OUT = CODEX_DIR / "commands"
REGISTRY_OUT = CODEX_DIR / "registry.json"
REPORT_OUT = CODEX_DIR / "compatibility-report.md"
README_OUT = CODEX_DIR / "README.md"

SOURCE_GROUPS = {
    "vertical": ROOT / "plugins" / "vertical-plugins",
    "partner": ROOT / "plugins" / "partner-built",
}

REWRITE_RULES = [
    (
        re.compile(r"`mcp__office__excel_\*`"),
        "`live spreadsheet editing tooling`",
    ),
    (
        re.compile(r"`mcp__office__powerpoint_\*`"),
        "`live presentation editing tooling`",
    ),
    (
        re.compile(r"managed-agent / CMA mode", re.IGNORECASE),
        "headless Codex mode",
    ),
    (
        re.compile(r"Cowork plugin mode", re.IGNORECASE),
        "interactive live-document mode",
    ),
    (
        re.compile(r"python /mnt/skills/public/xlsx/recalc\.py"),
        "python scripts/verify_xlsx.py",
    ),
    (
        re.compile(r"python recalc\.py"),
        "python scripts/verify_xlsx.py",
    ),
]

CLAUDE_PROFILE_PATH = re.compile(
    r"`~/.claude/plugins/config/claude-for-legal/([a-z0-9-]+)/CLAUDE\.md`",
    re.IGNORECASE,
)

FINDING_PATTERNS = [
    ("claude_plugin", re.compile(r"\bclaude plugin\b", re.IGNORECASE)),
    ("cowork", re.compile(r"\bCowork\b")),
    ("managed_agent", re.compile(r"\bManaged Agent\b", re.IGNORECASE)),
    ("claude_runtime", re.compile(r"/home/claude|\bClaude will have access\b|`present_files`", re.IGNORECASE)),
    ("claude_profile_path", re.compile(r"~/.claude/plugins/config/claude-for-legal/", re.IGNORECASE)),
    ("office_tooling", re.compile(r"mcp__office__")),
    ("mnt_skills", re.compile(r"/mnt/skills/public")),
    ("user_data_mount", re.compile(r"/mnt/user-data")),
    ("callable_agents", re.compile(r"\bcallable_agents\b")),
    ("handoff_request", re.compile(r"\bhandoff_request\b")),
]


@dataclass
class ExportedItem:
    plugin: str
    source_group: str
    kind: str
    name: str
    source: str
    destination: str
    findings: list[str]


def clean_output() -> None:
    CODEX_DIR.mkdir(parents=True, exist_ok=True)
    if SKILLS_OUT.exists():
        shutil.rmtree(SKILLS_OUT)
    if COMMANDS_OUT.exists():
        shutil.rmtree(COMMANDS_OUT)
    for path in (REGISTRY_OUT, REPORT_OUT, README_OUT):
        if path.exists():
            path.unlink()
    SKILLS_OUT.mkdir(parents=True, exist_ok=True)
    COMMANDS_OUT.mkdir(parents=True, exist_ok=True)


def apply_rewrites(text: str) -> str:
    rewritten = text
    for pattern, replacement in REWRITE_RULES:
        rewritten = pattern.sub(replacement, rewritten)
    rewritten = CLAUDE_PROFILE_PATH.sub(
        lambda match: f"`the installed practice profile for {match.group(1)}`",
        rewritten,
    )
    return rewritten


def collect_findings(text: str) -> list[str]:
    found: list[str] = []
    for name, pattern in FINDING_PATTERNS:
        if pattern.search(text):
            found.append(name)
    return found


def wrap_markdown(text: str, source: Path, generated_at: str) -> str:
    banner = (
        f"> Generated by `scripts/build_codex_port.py` on `{generated_at}`.\n"
        f"> Source: `{source.relative_to(ROOT).as_posix()}`.\n"
        "> This is a first-pass Codex export. Review `codex/compatibility-report.md` before relying on legacy runtime instructions.\n\n"
    )
    return banner + apply_rewrites(text)


def copy_tree_with_rewrites(src: Path, dst: Path, generated_at: str) -> list[str]:
    shutil.copytree(src, dst, dirs_exist_ok=True)
    aggregated: set[str] = set()
    for path in dst.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix.lower() not in {".md", ".txt"}:
            continue
        text = path.read_text(encoding="utf-8")
        findings = collect_findings(text)
        aggregated.update(findings)
        path.write_text(
            wrap_markdown(text, src / path.relative_to(dst), generated_at),
            encoding="utf-8",
        )
    return sorted(aggregated)


def export_sources() -> list[ExportedItem]:
    generated_at = datetime.now(timezone.utc).astimezone().isoformat()
    exported: list[ExportedItem] = []

    for source_group, base in SOURCE_GROUPS.items():
        if not base.exists():
            continue
        for plugin_dir in sorted(p for p in base.iterdir() if p.is_dir()):
            plugin_name = plugin_dir.name

            skills_dir = plugin_dir / "skills"
            if skills_dir.exists():
                for skill_dir in sorted(p for p in skills_dir.iterdir() if p.is_dir()):
                    skill_md = skill_dir / "SKILL.md"
                    if not skill_md.exists():
                        continue
                    dst = SKILLS_OUT / plugin_name / skill_dir.name
                    findings = copy_tree_with_rewrites(skill_dir, dst, generated_at)
                    exported.append(
                        ExportedItem(
                            plugin=plugin_name,
                            source_group=source_group,
                            kind="skill",
                            name=skill_dir.name,
                            source=str(skill_dir.relative_to(ROOT).as_posix()),
                            destination=str(dst.relative_to(ROOT).as_posix()),
                            findings=findings,
                        )
                    )

            commands_dir = plugin_dir / "commands"
            if commands_dir.exists():
                for command_file in sorted(commands_dir.glob("*.md")):
                    dst_dir = COMMANDS_OUT / plugin_name
                    dst_dir.mkdir(parents=True, exist_ok=True)
                    dst = dst_dir / command_file.name
                    text = command_file.read_text(encoding="utf-8")
                    findings = collect_findings(text)
                    dst.write_text(
                        wrap_markdown(text, command_file, generated_at),
                        encoding="utf-8",
                    )
                    exported.append(
                        ExportedItem(
                            plugin=plugin_name,
                            source_group=source_group,
                            kind="command",
                            name=command_file.stem,
                            source=str(command_file.relative_to(ROOT).as_posix()),
                            destination=str(dst.relative_to(ROOT).as_posix()),
                            findings=sorted(findings),
                        )
                    )

    return exported


def read_mcp_servers(plugin_dir: Path) -> dict[str, object] | None:
    mcp_path = plugin_dir / ".mcp.json"
    if not mcp_path.exists():
        return None
    try:
        return json.loads(mcp_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {"error": f"Failed to parse {mcp_path.relative_to(ROOT).as_posix()}"}


def build_registry(items: list[ExportedItem]) -> dict[str, object]:
    plugins: dict[str, dict[str, object]] = {}

    for source_group, base in SOURCE_GROUPS.items():
        if not base.exists():
            continue
        for plugin_dir in sorted(p for p in base.iterdir() if p.is_dir()):
            plugins[plugin_dir.name] = {
                "source_group": source_group,
                "source_path": plugin_dir.relative_to(ROOT).as_posix(),
                "mcp": read_mcp_servers(plugin_dir),
                "skills": [],
                "commands": [],
            }

    for item in items:
        entry = {
            "name": item.name,
            "source": item.source,
            "destination": item.destination,
            "findings": item.findings,
        }
        bucket = "skills" if item.kind == "skill" else "commands"
        plugins[item.plugin][bucket].append(entry)

    generated_at = datetime.now(timezone.utc).astimezone().isoformat()
    return {
        "generated_at": generated_at,
        "plugins": plugins,
        "summary": {
            "skills": sum(1 for item in items if item.kind == "skill"),
            "commands": sum(1 for item in items if item.kind == "command"),
            "items_with_findings": sum(1 for item in items if item.findings),
        },
    }


def write_readme(registry: dict[str, object]) -> None:
    summary = registry["summary"]
    content = f"""# Codex Export

The generated export in this directory is produced by `python scripts/build_codex_port.py`.

- Skills: `{summary["skills"]}`
- Commands: `{summary["commands"]}`
- Items with compatibility findings: `{summary["items_with_findings"]}`

## Usage

- read generated exported skills from `skills/`
- read generated exported commands from `commands/`
- inspect generated `registry.json` for source mapping and connector metadata
- inspect generated `compatibility-report.md` before assuming a skill is fully Codex-native
- use hand-authored `coordinators/` and `task-packs/` for the managed-agent-to-Codex workflow layer

Do not hand-edit generated files such as `skills/`, `commands/`, `registry.json`, or `compatibility-report.md`. Update the canonical source under `plugins/` and regenerate.

`coordinators/` and `task-packs/` are hand-authored and intentionally preserved across rebuilds.
"""
    README_OUT.write_text(content, encoding="utf-8")


def write_report(items: list[ExportedItem]) -> None:
    findings_index: dict[str, list[ExportedItem]] = {}
    for item in items:
        for finding in item.findings:
            findings_index.setdefault(finding, []).append(item)

    lines = [
        "# Codex Compatibility Report",
        "",
        "Generated by `python scripts/build_codex_port.py`.",
        "",
        f"- Skills exported: `{sum(1 for item in items if item.kind == 'skill')}`",
        f"- Commands exported: `{sum(1 for item in items if item.kind == 'command')}`",
        f"- Items with findings: `{sum(1 for item in items if item.findings)}`",
        "",
        "## Findings",
        "",
    ]

    if not findings_index:
        lines.append("No compatibility findings were detected in the exported markdown.")
    else:
        for finding in sorted(findings_index):
            lines.append(f"### {finding}")
            lines.append("")
            for item in findings_index[finding]:
                lines.append(
                    f"- `{item.plugin}/{item.name}` ({item.kind}) -> `{item.destination}`"
                )
            lines.append("")

    lines.extend(
        [
            "## Interpretation",
            "",
            "- `claude_plugin`, `cowork`, and `managed_agent` indicate documentation tied to Anthropic packaging.",
            "- `claude_runtime` indicates assumptions about Claude-specific home paths or UI primitives.",
            "- `claude_profile_path` indicates references to Claude plugin config paths that need Codex-side adaptation.",
            "- `office_tooling` indicates direct references to Claude Office tool names that require manual Codex replacement.",
            "- `mnt_skills` indicates hidden path dependencies that must be replaced with repo-local guidance.",
            "- `user_data_mount` indicates output assumptions tied to a Claude container mount.",
            "- `callable_agents` and `handoff_request` indicate Anthropic multi-agent orchestration concepts that are not native Codex runtime primitives here.",
        ]
    )

    REPORT_OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    clean_output()
    items = export_sources()
    registry = build_registry(items)
    REGISTRY_OUT.write_text(json.dumps(registry, indent=2), encoding="utf-8")
    write_readme(registry)
    write_report(items)
    print(
        json.dumps(
            {
                "status": "ok",
                "skills": registry["summary"]["skills"],
                "commands": registry["summary"]["commands"],
                "items_with_findings": registry["summary"]["items_with_findings"],
            }
        )
    )


if __name__ == "__main__":
    main()
