#!/usr/bin/env python3
"""Summarize Anthropic managed-agent cookbooks into a Codex migration map."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import json

import yaml


ROOT = Path(__file__).resolve().parents[1]
MANAGED = ROOT / "managed-agent-cookbooks"
OUT_MD = ROOT / "codex" / "managed-agent-map.md"
OUT_JSON = ROOT / "codex" / "managed-agent-map.json"


def read_yaml(path: Path) -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def normalize_tool(tool: dict) -> str:
    tool_type = tool.get("type", "unknown")
    if tool_type == "mcp_toolset":
        return f"mcp_toolset:{tool.get('mcp_server_name', 'unknown')}"
    return tool_type


def summarize_agent(agent_dir: Path) -> dict:
    agent_yaml = read_yaml(agent_dir / "agent.yaml")
    subagents_dir = agent_dir / "subagents"
    subagents = []
    if subagents_dir.exists():
        for path in sorted(subagents_dir.glob("*.yaml")):
            data = read_yaml(path)
            subagents.append(
                {
                    "name": data.get("name", path.stem),
                    "file": path.relative_to(ROOT).as_posix(),
                    "tools": [normalize_tool(tool) for tool in data.get("tools", [])],
                    "mcp_servers": [server.get("name") for server in data.get("mcp_servers", [])],
                }
            )

    return {
        "name": agent_yaml.get("name", agent_dir.name),
        "model": agent_yaml.get("model"),
        "source_dir": agent_dir.relative_to(ROOT).as_posix(),
        "system_file": agent_yaml.get("system", {}).get("file"),
        "append": agent_yaml.get("system", {}).get("append"),
        "tools": [normalize_tool(tool) for tool in agent_yaml.get("tools", [])],
        "mcp_servers": [server.get("name") for server in agent_yaml.get("mcp_servers", [])],
        "skills": agent_yaml.get("skills", []),
        "callable_agents": [agent.get("manifest") for agent in agent_yaml.get("callable_agents", [])],
        "subagents": subagents,
    }


def derive_codex_strategy(agent: dict) -> dict:
    return {
        "suggested_codex_shape": "coordinator-skill-plus-local-workers",
        "orchestration_notes": [
            "Translate the top-level agent into a Codex workflow guide or coordinator skill.",
            "Translate each callable subagent into a bounded worker responsibility or subtask prompt.",
            "Treat MCP server references as optional connector dependencies that must be configured separately.",
            "Replace Anthropic handoff semantics with explicit Codex task sequencing or spawned workers when appropriate.",
        ],
        "migration_risks": [
            "Anthropic agent tool schemas do not map one-to-one to Codex runtime tools.",
            "Managed-agent depth and steering assumptions require manual orchestration design.",
        ],
    }


def build_map() -> dict:
    agents = []
    for agent_dir in sorted(p for p in MANAGED.iterdir() if p.is_dir()):
        summary = summarize_agent(agent_dir)
        summary["codex_strategy"] = derive_codex_strategy(summary)
        agents.append(summary)

    return {
        "generated_at": datetime.now(timezone.utc).astimezone().isoformat(),
        "agents": agents,
        "summary": {
            "agent_count": len(agents),
            "subagent_count": sum(len(agent["subagents"]) for agent in agents),
        },
    }


def write_markdown(data: dict) -> None:
    lines = [
        "# Managed Agent Map",
        "",
        "Generated by `python scripts/map_managed_agents.py`.",
        "",
        f"- Agents: `{data['summary']['agent_count']}`",
        f"- Subagents: `{data['summary']['subagent_count']}`",
        "",
        "This report maps the legacy Anthropic managed-agent cookbooks into a Codex migration view.",
        "",
    ]

    for agent in data["agents"]:
        lines.extend(
            [
                f"## {agent['name']}",
                "",
                f"- Source: `{agent['source_dir']}`",
                f"- Model: `{agent['model']}`",
                f"- System prompt: `{agent['system_file']}`",
                f"- Top-level tools: `{', '.join(agent['tools']) if agent['tools'] else 'none'}`",
                f"- MCP servers: `{', '.join(agent['mcp_servers']) if agent['mcp_servers'] else 'none'}`",
                f"- Callable manifests: `{', '.join(agent['callable_agents']) if agent['callable_agents'] else 'none'}`",
                "",
                "Suggested Codex shape:",
                f"- `{agent['codex_strategy']['suggested_codex_shape']}`",
                "",
                "Subagents:",
            ]
        )

        if agent["subagents"]:
            for subagent in agent["subagents"]:
                lines.append(
                    f"- `{subagent['name']}` via `{subagent['file']}` | tools: `{', '.join(subagent['tools']) if subagent['tools'] else 'none'}` | mcp: `{', '.join(subagent['mcp_servers']) if subagent['mcp_servers'] else 'none'}`"
                )
        else:
            lines.append("- none")

        lines.extend(
            [
                "",
                "Migration notes:",
            ]
        )
        for note in agent["codex_strategy"]["orchestration_notes"]:
            lines.append(f"- {note}")

        lines.extend(
            [
                "",
                "Migration risks:",
            ]
        )
        for risk in agent["codex_strategy"]["migration_risks"]:
            lines.append(f"- {risk}")

        lines.append("")

    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    data = build_map()
    OUT_JSON.write_text(json.dumps(data, indent=2), encoding="utf-8")
    write_markdown(data)
    print(json.dumps(data["summary"]))


if __name__ == "__main__":
    main()
